---
title: "Mapping cruise data from BROKE-West, with R"
author: "Michael Sumner and Tomas Remenyi"
date: "8/27/2015"
output: html_document
---

```{r,echo=FALSE,message=FALSE}
library(fields)
```

Get some bathymetric data and save it (see Appendix). 

Load the bathymetry data. 
```{r}
load("data/broke_bathy.RData")
```

Read the zooplankton data. 

```{r}
library(readxl)
bw <- read_excel("data/BW-Zooplankton_env.xls")
summary(bw[,1:10])

```

Plot the temperature data. 

```{r}
plot(bw$temp)
```

Create a grid to interpolate onto. 

```{r}
library(raster)
xy <- as.matrix(bw[, c("Lon", "Lat")])
r0 <-  raster(extent(xy), ncol = 60, nrow = 50, crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0")
library(fields)
tps <- Tps(xy, bw$temp)
temp <- interpolate(r0, tps)
temp[temp < -1.8] <- NA_real_

tps <- Tps(xy, bw$`ice free days`)
ifd <- interpolate(r0, tps)

tps <- Tps(xy, bw$`chl a mg/m2)`/1000)
chl <- interpolate(r0, tps)

library(palr)
spal <- palr::sstPal(palette = TRUE)
plot(NA, asp = NA, xlab = "Longitude", ylab = "Latitude", xlim = c(20, 90), ylim = c(-70, -60))
plot(temp, add = TRUE, col = spal$cols, breaks = spal$breaks)
contour(temp, add = TRUE)
contour(bathy,  lwd = 2, lev = -1, add = TRUE); ##c(-5000, -4000, -3000, -500, -200))
points(xy, pch = 21, cex = 4, bg = sstPal(bw$temp))

# use model to predict values at all locations
plot(NA, asp = NA, xlab = "Longitude", ylab = "Latitude", xlim = c(20, 90), ylim = c(-70, -60))
plot(ifd, add = TRUE)
contour(ifd, add = TRUE)
contour(bathy,  lwd = 2, lev = -1, add = TRUE); ##c(-5000, -4000, -3000, -500, -200))

# use model to predict values at all locations
plot(NA, asp = NA, xlab = "Longitude", ylab = "Latitude", xlim = c(20, 90), ylim = c(-70, -60))
pal <- palr::chlPal(palette = TRUE)
plot(chl, add = TRUE, col = pal$cols, breaks = pal$breaks, legend = FALSE)
contour(chl, add = TRUE)
contour(bathy,  lwd = 2, lev = -1, add = TRUE); ##c(-5000, -4000, -3000, -500, -200))
points(xy, pch = 21, cex = 4, bg = chlPal(bw$`chl a mg/m2)`/1000))


```


# Appendix

```{r,eval=FALSE}
library(raadtools)
bathy1 <- aggregate(readtopo("etopo2", xylim = extent(15, 95, -75, -55)) , fact = 2, fun = mean)
gf <- focalWeight(bathy1, res(bathy1) * 6, "Gauss")
bathy <- focal(bathy1, gf)
save(bathy, file = "data/broke_bathy.RData")

```
```{r,eval=FALSE,echo=FALSE}
library(rmatio)
bathy0 <- read.mat("afternoon_exercise/broke_bathy.mat")
xynames <- c("lon", "lat")
len <- length(bathy0)
## you cannot change the xlim/ylim in R after the fact
lon <- unlist(bathy0[seq(1, len, by = 2)])
lat <- unlist(bathy0[seq(2, len, by = 2)])

```
